<?php
declare(strict_types=1);

namespace App\Http\Controllers;

use Swagger\Annotations as SWG;

/**
 * @SWG\Definition(
 *     definition="AboutMeUser",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="first_name",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="last_name",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="email",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="client_id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="job_role",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="job_dept",
 *      type="string"
 *  ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/CreatedUpdatedDates")
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="User",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="name",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="email",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="client_id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="job_role",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="job_dept",
 *      type="string"
 *  ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/CreatedUpdatedDates")
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="AuthUser",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="token",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="role",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="avatar",
 *      type="string"
 *  ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/User")
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="Topic",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="title",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="slug",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="focus_id",
 *      type="integer",
 *  ),
 *  @SWG\Property(
 *      property="introduction",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="has_practice",
 *      type="boolean"
 *  ),
 *  @SWG\Property(
 *      property="calendar_prompt_text",
 *      type="boolean"
 *  ),
 *  @SWG\Property(
 *      property="status",
 *      type="integer",
 *      description="1 - Draft | 2 - Review | 3 - Published",
 *  ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/CreatedByField"),
 *         @SWG\Schema(ref="#/definitions/CreatedUpdatedDates")
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="TopicOfUser",
 *     allOf={
 *         @SWG\Schema(ref="#/definitions/Topic"),
 *         @SWG\Schema(ref="#/definitions/ScheduledEvent"),
 *         @SWG\Schema(
 *             @SWG\Property(
 *                 property="progress",
 *                 ref="#/definitions/ProgressObject"
 *             )
 *         )
 *     }
 * );
 *
 * @SWG\DEfinition(
 *     definition="OffsetLimitData",
 *     @SWG\Property(
 *         property="offset",
 *         type="integer",
 *         default=0
 *     ),
 *     @SWG\Property(
 *         property="limit",
 *         type="integer",
 *         default=10
 *     ),
 * );
 *
 * @SWG\Definition(
 *     definition="ContentItem",
 *     allOf={
 *         @SWG\Schema(
 *      @SWG\Property(
 *         property="id",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="content_type",
 *         type="integer",
 *         description="article - 1, audio - 2, video - 3, tip - 4"
 *     ),
 *     @SWG\Property(
 *         property="focus_id",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="topic_id",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="primer_title",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="primer_content",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="reading_time",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="info_content_image",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="info_quick_tip",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="info_full_content",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="info_video_uri",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="info_audio_uri",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="info_source_title",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="info_source_link",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="has_reflection",
 *         type="boolean",
 *     ),
 *     @SWG\Property(
 *         property="reflection_help_text",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="status",
 *         type="integer",
 *         description="1 - draft, 2 - review, 3 - published"
 *     ),
 *     @SWG\Property(
 *         property="meta",
 *         @SWG\Property(
 *             property="primer_viewed",
 *             type="boolean"
 *         ),
 *         @SWG\Property(
 *             property="info_viewed",
 *             type="boolean"
 *         ),
 *         @SWG\Property(
 *             property="reflection_viewed",
 *             type="boolean"
 *         ),
 *         @SWG\Property(
 *             property="completed_at",
 *             type="string"
 *         ),
 *     ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/CreatedUpdatedDates"),
 *         @SWG\Schema(ref="#/definitions/ProgressObject")
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="Client",
 *     allOf={
 *         @SWG\Schema(
 *      @SWG\Property(
 *         property="id",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="name",
 *         type="string",
 *     ),
 *     @SWG\Property(
 *         property="content_model",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="primer_notice_timing",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="content_notice_timing",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="reflection_notice_timing",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="active",
 *         type="boolean",
 *     ),
 *     @SWG\Property(
 *         property="count_users",
 *         type="intteger",
 *     ),
 *          ),
 *          @SWG\Schema(ref="#/definitions/CreatedUpdatedDates"),
 *          @SWG\Schema(ref="#/definitions/CreatedByField")
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="Activity",
 *     allOf={
 *     @SWG\Schema(
 *          @SWG\Property(
 *              property="id",
 *              type="integer"
 *          ),
 *          @SWG\Property(
 *              property="image",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="first_name",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *              property="last_name",
 *              type="string"
 *          ),
 *          @SWG\Property(
 *               property="event",
 *               type="string"
 *          ),
 *          @SWG\Property(
 *               property="date",
 *               type="string"
 *          ),
 *          ),
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="CreatedUpdatedDates",
 *     @SWG\Property(
 *         property="created_at",
 *         type="string",
 *         description="Format(PHP): Y:m:d H:i:s O"
 *     ),
 *     @SWG\Property(
 *         property="updated_at",
 *         type="string",
 *         description="Format(PHP): Y:m:d H:i:s O"
 *     )
 * );
 *
 * @SWG\Definition(
 *     definition="CreatedByField",
 *     @SWG\Property(
 *         property="created_by",
 *         type="integer",
 *     )
 * );
 *
 * @SWG\Definition(
 *     definition="ProgressObject",
 *     @SWG\Property(
 *         property="total",
 *         type="integer",
 *     ),
 *     @SWG\Property(
 *         property="completed",
 *         type="integer",
 *     ),
 * );
 *
 * @SWG\Definition(
 *     definition="TopicArea",
 *     allOf={
 *         @SWG\Schema(
 *             @SWG\Property(
 *                 property="id",
 *                 type="integer"
 *             ),
 *             @SWG\Property(
 *                 property="focus_area_id",
 *                 type="integer"
 *             ),
 *             @SWG\Property(
 *                 property="topic_id",
 *                 type="integer"
 *             ),
 *             @SWG\Property(
 *                 property="topic",
 *                 type="object"
 *             ),
 *         )
 *     }
 * )
 *
 * @SWG\Definition(
 *  definition="FocusArea",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="id",
 *      type="integer",
 *      description="Focus Area ID"
 *  ),
 *  @SWG\Property(
 *      property="focus_id",
 *      type="integer",
 *      description="Focus ID"
 *  ),
 *  @SWG\Property(
 *      property="program_id",
 *      type="integer",
 *      description="Program ID"
 *  ),
 *  @SWG\Property(
 *      property="title",
 *      type="string",
 *      description="Focus title"
 *  ),
 *  @SWG\Property(
 *      property="status",
 *      type="integer",
 *      description="Focus status, available statuses: 1 - Draft | 2 - Review | 3 - Published",
 *  ),
 *  @SWG\Property(
 *      property="count_sessions",
 *      type="integer",
 *      description="Count of content items",
 *  ),
 *  @SWG\Property(
 *      property="count_topics",
 *      type="integer",
 *      description="Count of topics",
 *  ),
 *         ),
 *         @SWG\Schema(
 *             ref="#/definitions/CreatedUpdatedDates"
 *         ),
 *     }
 * );
 *
 * @SWG\Definition(
 *  definition="Focus",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="title",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="slug",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="status",
 *      type="integer",
 *      description="Focus status, available statuses: 1 - Draft | 2 - Review | 3 - Published",
 *  ),
 *  @SWG\Property(
 *      property="accent_color",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="image",
 *      type="string",
 *      description="Directed link to image"
 *  ),
 *  @SWG\Property(
 *      property="count_sessions",
 *      type="integer",
 *  ),
 *         ),
 *         @SWG\Schema(
 *             ref="#/definitions/CreatedUpdatedDates"
 *         )
 *     }
 * );
 *
 * @SWG\Definition(
 *     definition="ScheduledEvent",
 *     @SWG\Property(
 *          property="id",
 *          type="integer"
 *     ),
 *     @SWG\Property(
 *          property="user_id",
 *          type="integer"
 *     ),
 *     @SWG\Property(
 *          property="topic_id",
 *          type="integer"
 *     ),
 *     @SWG\Property(
 *          property="focus_id",
 *          type="integer"
 *     ),
 *     @SWG\Property(
 *          property="occurs_at",
 *          type="date",
 *          format="Y-m-d H:i:s O"
 *     ),
 * );
 *
 * @SWG\Definition(
 *  definition="Reflection",
 *     allOf={
 *         @SWG\Schema(
 *  @SWG\Property(
 *      property="id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="user_id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="content_item_id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="input",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="skipped",
 *      type="boolean",
 *  ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/CreatedUpdatedDates")
 *     }
 * );
 *
 * @SWG\Definition(
 *  definition="ScheduleTopicOverview",
 *  @SWG\Property(
 *      property="id",
 *      type="integer"
 *  ),
 *  @SWG\Property(
 *      property="overview_at",
 *      type="string",
 *      description="Format: Y-m-d H:i:s"
 *  ),
 *  @SWG\Property(
 *     property="user_id",
 *     type="integer"
 *  ),
 *  @SWG\Property(
 *     property="topic_id",
 *     type="integer"
 *  ),
 *  @SWG\Property(
 *     property="focus_id",
 *     type="integer"
 *  ),
 * );
 *
 * @SWG\Definition(
 *  definition="AdminBody",
 *  required={"email"},
 *  @SWG\Property(
 *      property="email",
 *      type="string",
 *  ),
 * );
 *
 * @SWG\Definition(
 *  definition="ProgramBody",
 *  required={"client_id", "name"},
 *  @SWG\Property(
 *      property="client_id",
 *      type="integer",
 *  ),
 *  @SWG\Property(
 *      property="name",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="status",
 *      type="integer",
 *     description="1, 2, 3"
 *  ),
 * );
 *
 * @SWG\Definition(
 *  definition="FocusBody",
 *  required={"title", "slug", "status"},
 *  @SWG\Property(
 *      property="program_id",
 *      type="integer",
 *      description="The Identificator of the existing Program"
 *  ),
 *  @SWG\Property(
 *      property="title",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="status",
 *      type="integer",
 *      description="available statuses: 1 - Draft | 2 - Review | 3 - Published",
 *  ),
 *  @SWG\Property(
 *      property="accent_color",
 *      type="string",
 *      description="In HEX format Example: #aaff00"
 *  ),
 *  @SWG\Property(
 *      property="image_url",
 *      type="string",
 *      description="Link to image"
 *  ),
 *  @SWG\Property(
 *      property="video_overview",
 *      type="string",
 *      description="Link to video"
 *  )
 * );
 *
 * @SWG\Definition(
 *  definition="ReflectionBody",
 *  @SWG\Property(
 *      property="content_item_id",
 *      type="integer",
 *      description="The Identificator of the existing Content Item Object"
 *  ),
 *  @SWG\Property(
 *      property="input",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="skipped",
 *      type="boolean",
 *  ),
 * );
 *
 *
 * @SWG\Definition(
 *  definition="TopicBodyData",
 *  required={
 *     "title",
 *     "status",
 *     "has_practice",
 *     "focus_id",
 *     "introduction",
 *     "status"
 * },
 *  @SWG\Property(
 *      property="title",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="slug",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="status",
 *      type="integer",
 *      description="1 - Draft | 2 - Review | 3 - Published",
 *  ),
 *  @SWG\Property(
 *      property="has_practice",
 *      type="boolean",
 *      description="available values: true - false | 1 : 0",
 *  ),
 *  @SWG\Property(
 *      property="introduction",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="focus_id",
 *      type="integer",
 *     description="Related Focus id"
 *  ),
 *  @SWG\Property(
 *      property="content_item_id",
 *      type="integer",
 *     description="Practice based Content Item ID"
 *  ),
 *   @SWG\Property(
 *     property="calendar_prompt_text",
 *     type="string",
 *     description="Calendar Prompt Text"
 *  ),
 * ),
 *
 * @SWG\Definition(
 *  definition="ScheduleTopicOverviewBody",
 *  required={"overview_at", "topic_id"},
 *  @SWG\Property(
 *     property="occurs_at",
 *     type="string",
 *     description="Format: Y-m-d H:i:s O (2019-12-31 23:59:59 +0300)"
 *  ),
 *  @SWG\Property(
 *      property="user_id",
 *      type="integer",
 *      description="Related User id"
 *  ),
 *  @SWG\Property(
 *      property="topic_id",
 *      type="integer",
 *      description="Related Topic id"
 *  ),
 * ),
 *
 * @SWG\Definition(
 *  definition="InviteEmailBody",
 *  required={"email"},
 *  @SWG\Property(
 *      property="email",
 *      type="string"
 *  ),
 * )
 *
 * @SWG\Definition(
 *     definition="InviteEmail",
 *     allOf={
 *         @SWG\Schema(
 *             @SWG\Property(
 *                 property="id",
 *                 type="integer"
 *             ),
 *             @SWG\Property(
 *                 property="email",
 *                 type="string"
 *             ),
 *             @SWG\Property(
 *                 property="status",
 *                 type="integer"
 *             ),
 *             @SWG\Property(
 *                 property="magic_link_token",
 *                 type="string"
 *             ),
 *         ),
 *         @SWG\Schema(ref="#/definitions/CreatedUpdatedDates")
 *     }
 * )
 *
 * @SWG\Definition(
 *     definition="GlobalSettings",
 *     @SWG\Property(
 *         property="primer_notification_time",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="content_notification_time",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="reflection_notification_time",
 *         type="integer"
 *     )
 * )
 *
 * @SWG\Definition(
 *     definition="UserSettings",
 *     @SWG\Property(
 *         property="tip_time",
 *         type="string"
 *     ),
 *     @SWG\Property(
 *         property="event_practice_email",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="event_practice_notification",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="random_acts_email",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="random_acts_notification",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="login_streak_email",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="login_streak_notification",
 *         type="integer"
 *     ),
 *     @SWG\Property(
 *         property="share_activity",
 *         type="integer"
 *     ),
 * )
 *
 * @SWG\Definition(
 *  definition="FocusSortParameter",
 *  @SWG\Property(
 *      property="sort",
 *      type="string"
 *  ),
 * ),
 *
 * @SWG\Definition(
 *     definition="Program",
 *     allOf={
 *     @SWG\Schema(
 *         @SWG\Property(
 *             property="id",
 *             type="integer",
 *         ),
 *         @SWG\Property(
 *             property="name",
 *             type="string",
 *         ),
 *         @SWG\Property(
 *             property="status",
 *             type="boolean",
 *         ),
 *     ),
 *     @SWG\Schema(ref="#/definitions/CreatedUpdatedDates")
 *     }
 * )
 *
 * @SWG\Definition(
 *     definition="Validation Error",
 *         @SWG\Property(
 *             property="errors",
 *             type="array",
 *             @SWG\Items(
 *                 @SWG\Property(
 *                     property="propertyName",
 *                     type="array",
 *                     @SWG\Items(
 *                         @SWG\Property(
 *                             property="message", type="string"
 *                         ),
 *                     ),
 *                 ),
 *             ),
 *         ),
 * );
 *
 * @SWG\Definition(
 *  definition="UserBody",
 *  @SWG\Property(
 *      property="first_name",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="last_name",
 *      type="string",
 *  ),
 *  @SWG\Property(
 *      property="job_dept",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="job_role",
 *      type="string"
 *  ),
 *  @SWG\Property(
 *      property="phone",
 *      type="string"
 *  )
 * );
 */

/**
 * Class SwaggerDefinitionController
 * @package App\Http\Controllers
 *
 */
class SwaggerDefinitionController extends ApiController
{
}
